### ISSUE TITLE
Editing a single section in a page remove all other sections

### ISSUE THREAD

**Issue by pulkomandy** [xwikisas/application-documentation#3]
When editing a section of a page (using the edit link next to a header in the page), all other sections are removed from the page when saving.

To reproduce:

- Create a page in the application-documentation
- Add two or more headers (level 1) with a paragraph of text in them
- Click the edit button next to the first header
- Click the save button

Expected result: the page is not modified since no change was made

Actual result: only the first header and paragraph remains, everything else disappears from the page.

Workaround: always edit the whole page instead of one section at a time. But this is a bit unconvenient and the risk for data loss by using the section edit button is high.

**Comment by michitux** [comment]
On which version of XWiki is this? This sounds like issue [XWIKI-19820](https://jira.xwiki.org/browse/XWIKI-19820) which has been fixed in XWiki 14.4.2, 13.10.7 and 14.5 which have all been released recently.

**Comment by pulkomandy** [comment]
We are currently running version 13.10.3, I will see if we can update.

**Comment by pulkomandy** [comment]
Hello,
I have installed xwiki 13.10.7 and this problem seems to be fixed. However I have a new problem now.
When editing a page (in or outside of the application-documentation), instead of the page content, the editor show:

    #getRenderedContent($source)

And the source view shows:

    #convert($text $toHTML $fromHTML $stripHTMLEnvelope)

If I save the edit from this point, the page or section that I tried to edit is replaced with this as well.

Any idea what is happening? Maybe I should report this elsewhere as this does not seem related to application-documentation?

**Comment by michitux** [comment]
@pulkomandy Can you check if this only happens with the WYSIWYG editor or also with the wiki editor (as advanced user)? The correct place to report this is https://jira.xwiki.org, if it only affects the WYSIWYG editor, it should be reported on the [CKEditor Integration](https://jira.xwiki.org/browse/CKEDITOR) project there, otherwise the [XWiki Platform](https://jira.xwiki.org/browse/XWIKI) project.

**Comment by pulkomandy** [comment]
Thanks, I have reported this new problem in https://jira.xwiki.org/browse/CKEDITOR-477 as it happens only in the WYSIWYG editor. I think we can close this issue now since the original problem is solved.
